export type IncidentCatalogOption = {
  id: string;
  label: string;
  options: string[];
};

export const INCIDENT_CATALOGS: IncidentCatalogOption[] = [
  {
    id: 'tipo_incidente',
    label: 'Tipo de incidente',
    options: ['Personal', 'Instalaciones', 'Equipos', 'Ambiental', 'Vehicular'],
  },
  {
    id: 'gravedad',
    label: 'Gravedad',
    options: ['Leve', 'Moderado', 'Grave', 'Mayor'],
  },
  {
    id: 'clasificacion',
    label: 'Clasificacion',
    options: ['Primeros Auxilios', 'Tratamiento Medico', 'Dias Caidos'],
  },
  {
    id: 'hubo_lesionados',
    label: 'Hubo lesionados',
    options: ['Si', 'No', 'No Aplica'],
  },
  {
    id: 'permiso_trabajo',
    label: 'Permiso de trabajo',
    options: ['Si', 'No', 'No Aplica'],
  },
  {
    id: 'tipo_servicio',
    label: 'Tipo de servicio',
    options: [
      'Agua Dulce',
      'Agua de Purga',
      'Agua Potable',
      'Ultra Vacio',
      'Vacio',
      'Porta Contenedores',
      'Cargas Generales',
      'Obras Civil',
      'Soldadura',
      'Motobomba',
      'Mecanico',
      'Electricista',
      'Base Operativa',
      'Logistica',
      'Compras',
      'Supervision',
    ],
  },
  {
    id: 'condicion_climatica',
    label: 'Condicion climatica',
    options: ['Despejado', 'Lluvia', 'Nieve', 'Nublado', 'Niebla'],
  },
  {
    id: 'condicion_luz',
    label: 'Condicion de luz',
    options: ['Claro', 'Media', 'Oscura', 'Penunbra'],
  },
  {
    id: 'tipo_terreno',
    label: 'Tipo de terreno',
    options: [
      'Asfalto Llano',
      'Asfalto Pendiente',
      'Asfalto Curva',
      'Ripio Llano',
      'Ripio Pendiente',
      'Ripio Curva',
      'Caminos Consolidado',
      'Camino No Consolidado',
    ],
  },
  {
    id: 'condicion_ruta_terreno',
    label: 'Condicion ruta/terreno',
    options: ['Seco', 'Barroso', 'Hielo', 'Humedo', 'Resbaloso'],
  },
  {
    id: 'epp',
    label: 'Elementos de proteccion personal',
    options: ['Cumple', 'No cumple'],
  },
  {
    id: 'naturaleza_lesion',
    label: 'Naturaleza de la lesion',
    options: [
      'Amputaciones',
      'Heridas punzantes o cortantes',
      'Efectos de las radiaciones',
      'Lesiones oculares',
      'Torceduras y esguinces',
      'Asfixia',
      'Irritacion/ Inflamacion de la piel',
      'Fracturas',
      'Luxaciones',
      'Traumatismos superficiales',
      'Conmociones y traumatismos internos',
      'Distensiones musculares',
      'Intoxicaciones',
      'Perdida del globo ocular',
      'Contusiones y aplastamientos',
      'Efectos de la electricidad',
      'Lesiones multiples',
      'Quemaduras',
      'No aplica',
    ],
  },
  {
    id: 'zona_cuerpo',
    label: 'Zona del cuerpo afectada',
    options: [
      'Abdomen (incluye organos internos)',
      'Antebrazo',
      'Aparato digestivo en general',
      'Aparato respiratorio en general',
      'Boca (incluye labios, dientes, lengua)',
      'Brazo Derecho',
      'Brazo Izquierdo',
      'Cabeza, torax, miembros sup. (ubicaciones multiples)',
      'Cadera',
      'Cara',
      'Codo Derecho',
      'Codo Izquierdo',
      'Cuello',
      'Cuerpo entero',
      'Dedos de las manos',
      'Dedos de los pies',
      'Espalda',
      'Hombro',
      'Mano Izquierda',
      'mano Derecha',
    ],
  },
  {
    id: 'area_evento',
    label: 'Area donde sucedio el evento',
    options: [
      'Oficinas/ Edificios administrativos',
      'Sector de Carga/ descarga de camiones',
      'Obradores',
      'Area de tratamiento/ descarga de efluentes liquidos',
      'Tanques de almacenaje de producto',
      'Excavacion',
      'Taller',
      'Galpon',
      'Obra',
      'Deposito de insumos/ Materiales',
      'Area operativa',
      'Instalacion electrica',
      'Deposito de residuos',
    ],
  },
  {
    id: 'tipo_tarea',
    label: 'Tipo de tarea',
    options: [
      'Atencion de maquinas',
      'Inspeccion de equipos/ instalaciones',
      'Preparacion de comidas',
      'Tareas de albanileria, carpinteria, pintura',
      'Tareas generales de obra',
      'Traslado de un lugar a otro',
      'Carga/ descarga de producto',
      'Izaje de Materiales',
      'Reparacion de canerias',
      'Tareas Electricas',
      'Tareas operativas habituales',
      'Limpieza',
      'Reparacion de equipos/ vehiculos',
      'Tareas de oficina',
    ],
  },
  {
    id: 'forma_accidente',
    label: 'Forma del accidente',
    options: [
      'Aprisionamiento',
      'Caida de un mismo nivel',
      'Contacto con sust. u objetos ardientes o muy calientes',
      'Exposicion a radiaciones ionizantes',
      'Exposicion o contacto con la corriente electrica',
      'Atrapada por o entre objetos',
      'Choque contra o golpes por objetos',
      'Derrumbe',
      'Esfuerzo excesivo',
      'Caida de un lugar elevado',
      'Proyeccion de Particulas',
      'No aplica',
    ],
  },
  {
    id: 'agente_material',
    label: 'Agente material causante',
    options: [
      'Agentes biologicos',
      'Aparatos de mando y de control.',
      'Escaleras, rampas moviles, andamios.',
      'Herramientas electricas manuales',
      'Materiales de construccion sin instalar',
      'Otras maquinas fijas',
      'Recipientes de presion',
      'Ambiente de trabajo',
      'Explosiones',
      'Maquinas (Equipos pesados y/o viales)',
      'Medios de transporte liviano',
      'Animales/ insectos',
    ],
  },
  {
    id: 'condiciones_inseguras',
    label: 'Condiciones inseguras',
    options: [
      'Apuntalamiento/ condicion de zanja inadecuado',
      'Estiba inadecuada',
      'Falta de equipos de proteccion personal',
      'Herramientas y equipos faltantes o inadecuados',
      'Resguardo inadecuado en maquinas/ instalaciones',
      'Sin condiciones inseguras',
      'Falta de iluminacion',
      'Senalizacion inadecuada',
      'Dispositivos de seguridad bloqueados',
      'Falta de orden y limpieza',
      'No hubieron',
    ],
  },
  {
    id: 'actos_inseguros',
    label: 'Actos inseguros',
    options: [
      'Acceder a equipos/ instalaciones por medios no seguros',
      'Empleo inadecuado de herramientas y equipos',
      'Operacion a velocidad inadecuada',
      'Transitar o trabajar en areas peligrosas sin proteccion',
      'No uso de EPP',
      'Llevar a cabo operaciones sin previo adiestramiento',
      'Uso inadecuado de sustancias quimicas',
      'Bloquear o quitar dispositivos de seguridad',
      'Trabajos sin autorizacion',
      'Sin acto inseguro',
    ],
  },
  {
    id: 'cargo',
    label: 'Cargo',
    options: [
      'Supervisor Operativo',
      'Supervisor HSE',
      'Conductor',
      'Mecanico',
      'Electricista',
      'Soldador',
      'Amolador',
      'Of. Especializado',
      'Oficial',
      'Medio Oficial',
      'Ayudante',
    ],
  },
];

export const getCatalogOptions = (id: string): string[] => {
  return INCIDENT_CATALOGS.find((catalog) => catalog.id === id)?.options ?? [];
};
